variable "env" {}
variable "vpc" {}
variable "default_vpc_id" {}
variable "docdb" {}
variable "elasticache" {}
variable "rds" {}
variable "rabbitmq" {}
variable "alb" {}
variable "apps" {}
variable "bastion_cidr" {}
